use cxx_qt_build::{CxxQtBuilder, QmlFile, QmlModule};

fn main() {
    CxxQtBuilder::new_qml_module(
        QmlModule::new("org.tuxstack.app")
            .qml_file(QmlFile::from("qml/I18n.qml").singleton(true))
            .qml_files([
                "qml/Main.qml",
                "qml/pages/OverviewPage.qml",
                "qml/pages/ContainersPage.qml",
                "qml/pages/ImagesPage.qml",
                "qml/pages/NetworksPage.qml",
                "qml/pages/VolumesPage.qml",
                "qml/pages/ActivityMonitorPage.qml",
                "qml/pages/CommandsPage.qml",
                "qml/pages/DevicesPage.qml",
                "qml/pages/ComposePage.qml",
                "qml/pages/SettingsPage.qml",
                "qml/components/AppSidebar.qml",
                "qml/components/SidebarSection.qml",
                "qml/components/SidebarItem.qml",
                "qml/components/SidebarCollapseButton.qml",
                "qml/components/PageHeader.qml",
                "qml/components/LoadingView.qml",
                "qml/components/EmptyState.qml",
                "qml/components/ErrorBanner.qml",
                "qml/components/StatusBadge.qml",
                "qml/components/containers/ContainerContextMenu.qml",
                "qml/components/containers/ContainerDetailPanel.qml",
                "qml/components/containers/ContainerGroupInfoView.qml",
                "qml/components/containers/ContainerGroupItem.qml",
                "qml/components/containers/ContainerFilesView.qml",
                "qml/components/containers/ContainerInfoView.qml",
                "qml/components/containers/ContainerListItem.qml",
                "qml/components/containers/ContainerListPanel.qml",
                "qml/components/containers/ContainerLogsView.qml",
                "qml/components/containers/ContainerStatsView.qml",
                "qml/components/containers/ContainerTerminalView.qml",
                "qml/components/LocalFuseFilesView.qml",
                "qml/components/ResourceSummaryCard.qml",
                "qml/components/SearchField.qml",
                "qml/components/ImageListPanel.qml",
                "qml/components/ImageListItem.qml",
                "qml/components/ImageDetailPanel.qml",
                "qml/components/PropertySection.qml",
                "qml/components/PropertyList.qml",
                "qml/components/PropertyRow.qml",
                "qml/components/KeyValueTable.qml",
                "qml/components/ImageUsedByList.qml",
                "qml/components/NetworkListPanel.qml",
                "qml/components/NetworkListItem.qml",
                "qml/components/NetworkDetailPanel.qml",
                "qml/components/NetworkContainerList.qml",
                "qml/components/VolumeListPanel.qml",
                "qml/components/VolumeListItem.qml",
                "qml/components/VolumeDetailPanel.qml",
                "qml/components/VolumeInfoView.qml",
                "qml/components/VolumeFilesView.qml",
                "qml/components/ImageFilesView.qml",
                "qml/components/VolumeUsedByList.qml",
                "qml/components/VolumeKeyValueEditor.qml",
                "qml/dialogs/CreateNetworkDialog.qml",
                "qml/dialogs/RemoveNetworkDialog.qml",
                "qml/dialogs/CreateVolumeDialog.qml",
                "qml/dialogs/RemoveVolumeDialog.qml",
                "qml/dialogs/PruneVolumesDialog.qml",
                "qml/dialogs/ExportVolumeDialog.qml",
                "qml/dialogs/CloneVolumeDialog.qml",
                "qml/dialogs/LocalFuseFilePreviewDialog.qml",
                "qml/dialogs/LocalFuseFilePropertiesDialog.qml",
                "qml/dialogs/PullImageDialog.qml",
                "qml/dialogs/RemoveImageDialog.qml",
                "qml/dialogs/ExportImageDialog.qml",
                "qml/dialogs/containers/CreateContainerDialog.qml",
                "qml/dialogs/containers/KillContainerDialog.qml",
                "qml/dialogs/containers/RemoveContainerDialog.qml",
                "qml/dialogs/containers/RemoveContainerGroupDialog.qml",
                "qml/dialogs/containers/RenameContainerDialog.qml",
                "qml/dialogs/ErrorDetailsDialog.qml",
            ])
            .depends([
                "QtCore",
                "QtQuick",
                "QtQuick.Controls",
                "QtQuick.Dialogs",
                "QtQuick.Layouts",
                "org.kde.kirigami",
                "org.kde.ki18n",
            ]),
    )
    .qrc_resources(["qml/assets/io.github.tuxstack.TuxStack.png"])
    .cpp_file("src/bridge/application_icon.cpp")
    .qt_module("Qml")
    .qt_module("Quick")
    .qt_module("QuickControls2")
    .qt_module("QuickLayouts")
    .qt_module("QuickDialogs2")
    .files([
        "src/bridge/app_bridge.rs",
        "src/bridge/application_icon.rs",
        "src/bridge/container_live_bridge.rs",
        "src/bridge/container_terminal_bridge.rs",
        "src/bridge/containers_bridge.rs",
        "src/bridge/local_fuse_files_bridge.rs",
        "src/bridge/resource_bridges.rs",
        "src/bridge/terminal_settings_bridge.rs",
    ])
    .build();
}
