[package]
name = "tuxstack"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Native Docker management application for KDE Plasma"
rust-version.workspace = true
default-run = "tuxstack"

[[bin]]
name = "tuxstack"
path = "src/main.rs"

[dependencies]
tuxstack-client = { path = "../tuxstack-client" }
tuxstack-domain = { path = "../tuxstack-domain" }
tuxstack-protocol = { path = "../tuxstack-protocol" }
chrono = { workspace = true }
cxx = "1"
cxx-qt = "0.9"
cxx-qt-lib = { version = "0.9", features = ["qt_full"] }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde_json = { workspace = true }
futures-util = { workspace = true }
vt100 = "0.16.2"

[build-dependencies]
cxx-qt-build = "0.9"
