// Prevents additional console window on Windows in release, DO NOT REMOVE!!
#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

mod client;

use client::DaemonClient;

slint::include_modules!();

fn container_to_data(c: &tuxstack_common::ContainerInfo) -> ContainerData {
    ContainerData {
        id: c.id.clone().into(),
        name: c.name.clone().into(),
        image: c.image.clone().into(),
        status: c.status.as_str().into(),
        cpu: c
            .cpu_usage
            .map(|v| format!("{:.1}%", v))
            .unwrap_or_else(|| "-".to_string())
            .into(),
        memory: c
            .memory_usage
            .map(|v| format!("{:.1} MB", v as f64 / 1_048_576.0))
            .unwrap_or_else(|| "-".to_string())
            .into(),
    }
}

fn main() -> anyhow::Result<()> {
    let ui = MainWindow::new()?;

    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_io()
        .enable_time()
        .build()?;

    let handle = rt.handle().clone();

    // Detect system status on startup
    let weak = ui.as_weak();
    handle.spawn(async move {
        detect_system(weak).await;
    });

    // Fetch containers on startup
    let weak = ui.as_weak();
    handle.spawn(async move {
        refresh_containers(weak).await;
    });

    // Connect refresh button
    let weak = ui.as_weak();
    ui.global::<AppState>().on_request_refresh(move || {
        let h = handle.clone();
        let w = weak.clone();
        h.spawn(async move {
            refresh_containers(w).await;
        });
    });

    ui.run()?;
    Ok(())
}

async fn detect_system(ui: slint::Weak<MainWindow>) {
    let client = DaemonClient::connect().await;

    match client {
        Ok(mut c) => match c.detect().await {
            Ok(status) => {
                let _ = ui.upgrade_in_event_loop(move |ui| {
                    let state = ui.global::<AppState>();
                    state.set_docker_installed(status.docker_available);
                    state.set_incus_installed(status.incus_available);
                    state.set_docker_status_text(
                        if status.docker_available {
                            "Docker: ✅ 已安装".into()
                        } else {
                            "Docker: ❌ 未检测到".into()
                        },
                    );
                    state.set_incus_status_text(
                        if status.incus_available {
                            "Incus: ✅ 已安装".into()
                        } else {
                            "Incus: ❌ 未检测到".into()
                        },
                    );
                });
            }
            Err(e) => {
                tracing::error!("detect failed: {e}");
            }
        },
        Err(_) => {
            let _ = ui.upgrade_in_event_loop(|ui| {
                let state = ui.global::<AppState>();
                state.set_docker_status_text("Docker: 未连接到 daemon".into());
                state.set_incus_status_text("Incus: 未连接到 daemon".into());
                state.set_docker_installed(false);
                state.set_incus_installed(false);
            });
        }
    }
}

async fn refresh_containers(ui: slint::Weak<MainWindow>) {
    let mut client = match DaemonClient::connect().await {
        Ok(c) => c,
        Err(_) => return,
    };

    match client.list_containers(true).await {
        Ok(containers) => {
            let data_vec: Vec<ContainerData> =
                containers.iter().map(container_to_data).collect();

            let running_count = containers
                .iter()
                .filter(|c| matches!(c.status, tuxstack_common::ContainerStatus::Running))
                .count() as i32;
            let total = containers.len() as i32;

            // Build model inside the event loop (avoids Rc<VecModel> !Send issue)
            let _ = ui.upgrade_in_event_loop(move |ui| {
                let state = ui.global::<AppState>();
                state.set_containers(data_vec.as_slice().into());
                // Update Slint SystemStatus (the one generated by slint!)
                state.set_sys_status(SystemStatus {
                    docker_available: true,
                    incus_available: false,
                    containers_running: running_count,
                    containers_total: total,
                });
                state.set_show_welcome(false);
            });
        }
        Err(e) => {
            tracing::error!("refresh failed: {e}");
        }
    }
}
