[package]
name = "tuxstack-cli"
version.workspace = true
edition.workspace = true

[dependencies]
tuxstack-common = { path = "../common" }
tuxstack-daemon = { path = "../daemon" }
tokio = { workspace = true, features = ["rt", "io-util", "net"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }

[target.'cfg(unix)'.dependencies]
tokio = { workspace = true, features = ["net"] }
